Algoritmo "média de idade"

Var

idade1, idade2 : inteiro
nome1, nome2 : caractere
media : real

Inicio
      escreval("Nome da primeira pessoa: ")
      leia(nome1)
      escreval("idade: ")
      leia(idade1)
      escreval("Nome da segunda pessoa: ")
      leia(nome2)
      escreval("idade: ")
      leia(idade2)

      media <- (idade1 + idade2) / 2


      escreval("A media entre as idades é: ", media)



Fimalgoritmo