Algoritmo "Retângulo"

Var

base, altura, area, perimetro, diagonal : real

Inicio

escreval("Digite a base: ")
leia(base)
escreval("Digite a altura: ")
leia(Altura)

            perimetro <- 2 * base + 2 * altura
            diagonal  <- RaizQ(base^2 + altura^2))
            area      <- base * altura


escreval("O perimetro do retângulo é: ", perimetro:8:4)
escreval("A diagonal do retânulo é: ", diagonal:8:4)
escreval("A area do retângulo é:", area:8:4)



Fimalgoritmo